import logging
import datetime
from typing import Optional, Dict, Any
from app.config import settings
from app.schemas.recommendation import AIExplainRequest, AIExplainResponse

logger = logging.getLogger(__name__)


class GroqExplanationService:
    """
    Groq AI explanation service with robust error handling, prompt guardrails,
    and a deterministic scientific fallback generator.
    """

    @classmethod
    def generate_explanation(cls, request: AIExplainRequest) -> AIExplainResponse:
        api_key = settings.get_groq_api_key()
        model_name = settings.GROQ_MODEL_NAME or "llama-3.3-70b-versatile"

        if not api_key:
            logger.info("Groq API key not found in environment. Generating deterministic expert fallback explanation.")
            return cls._build_deterministic_fallback(
                request=request,
                reason="Groq API key is not configured in backend environment."
            )

        try:
            from groq import Groq
            client = Groq(api_key=api_key)

            # Build structured scientific context from actual database results
            context_summary = cls._format_scientific_context(request)

            system_prompt = (
                "You are a Senior Food Packaging Scientist and Polymer Engineer. "
                "Your objective is to provide a concise, rigorous technical explanation of the recommended packaging materials "
                "for the specified food commodity.\n\n"
                "STRICT RULES:\n"
                "1. Base your explanation strictly on the provided material barrier data (OTR, WVTR, tensile strength, recyclability).\n"
                "2. DO NOT change the algorithmic ranks or total scores.\n"
                "3. DO NOT invent fake test values, citations, or universal shelf-life guarantees.\n"
                "4. Clearly highlight the primary degradation mechanism (e.g. moisture uptake, lipid oxidation, respiration/anaerobic risk, texture loss).\n"
                "5. Explain key material trade-offs (e.g. barrier performance vs recyclability/cost).\n"
                "6. Emphasize that actual shelf-life requires physical migration checks, seal testing, and real-time storage trials."
            )

            user_prompt = (
                f"Please provide an expert packaging analysis and ranking breakdown for the following case:\n\n"
                f"{context_summary}\n\n"
                f"Structure your response with:\n"
                f"### 1. Executive Summary & Critical Spoilage Mechanisms\n"
                f"### 2. Top Material Candidate Evaluation\n"
                f"### 3. Engineering Trade-offs & Circularity Assessment\n"
                f"### 4. Quality Control & Experimental Validation Requirements"
            )

            completion = client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.3,
                max_tokens=1000
            )

            ai_text = completion.choices[0].message.content

            return AIExplainResponse(
                explanation=ai_text,
                provider="Groq Cloud LLM",
                model_name=model_name,
                generated_at=datetime.datetime.utcnow(),
                is_fallback=False,
                status_message="AI explanation successfully generated by Groq."
            )

        except Exception as e:
            logger.warning(f"Groq API call failed or timed out ({str(e)}). Generating deterministic scientific fallback.")
            return cls._build_deterministic_fallback(
                request=request,
                reason=f"Groq provider service unavailable or rate-limited ({str(e)})."
            )

    @classmethod
    def _format_scientific_context(cls, request: AIExplainRequest) -> str:
        inp = request.inputs
        lines = [
            f"COMMODITY: {request.commodity_name} ({request.commodity_category})",
            f"- Moisture Content: {inp.moisture_content_pct or 'Unknown'} %",
            f"- Fat Content: {inp.fat_content_pct or 'Unknown'} %",
            f"- pH: {inp.ph or 'Unknown'}",
            f"- Target Shelf Life: {inp.target_shelf_life_days} days",
            f"- Storage Condition: {inp.storage_type} at {inp.storage_temp_c}°C, {inp.relative_humidity_pct}% RH",
            f"- Transport: {inp.transport_condition}, Cost Tier: {inp.cost_tier}, Sustainability Priority: {inp.sustainability_priority}",
            "\nTOP RANKED PACKAGING CANDIDATES (Deterministic Engine Results):"
        ]

        for cand in request.top_candidates[:4]:
            specs = cand.technical_specifications
            lines.append(
                f"\n[Rank #{cand.rank}] {cand.material_name} ({cand.structure}) - Score: {cand.total_score}/100\n"
                f"  - OTR: {specs.get('otr_cc_m2_day_atm')} cc/m²·day | WVTR: {specs.get('wvtr_g_m2_day')} g/m²·day\n"
                f"  - Recyclability: {specs.get('recyclability')} | Cost: ₹{specs.get('cost_inr_per_kg')}/kg\n"
                f"  - Subscores -> Moisture: {cand.score_breakdown.moisture_score}, Oxygen: {cand.score_breakdown.oxygen_score}, "
                f"Sustainability: {cand.score_breakdown.sustainability_score}, Cost: {cand.score_breakdown.cost_score}\n"
                f"  - Key Verdict: {cand.compatibility_verdict}\n"
                f"  - Reasons: {'; '.join(cand.reasons_for_ranking[:2])}\n"
                f"  - Warnings: {'; '.join(cand.warnings[:2]) if cand.warnings else 'None'}"
            )

        return "\n".join(lines)

    @classmethod
    def _build_deterministic_fallback(cls, request: AIExplainRequest, reason: str) -> AIExplainResponse:
        inp = request.inputs
        top_mat = request.top_candidates[0] if request.top_candidates else None

        if not top_mat:
            explanation = "No eligible packaging materials identified for the specified constraints."
        else:
            specs = top_mat.technical_specifications
            reasons_str = "\n- ".join(top_mat.reasons_for_ranking)
            warnings_str = "\n- ".join(top_mat.warnings) if top_mat.warnings else "No critical barrier or safety warnings identified."
            trade_offs_str = "\n- ".join(top_mat.trade_offs) if top_mat.trade_offs else "Standard commercial profile with balanced cost and barrier efficiency."

            explanation = (
                f"### 1. Executive Summary & Critical Spoilage Mechanisms\n"
                f"For **{request.commodity_name}** stored under **{inp.storage_type}** conditions ({inp.storage_temp_c}°C, {inp.relative_humidity_pct}% RH), "
                f"the primary quality degradation vectors include moisture equilibration, atmospheric lipid oxidation, and volatile loss. "
                f"To attain the target shelf life of **{inp.target_shelf_life_days} days**, packaging must provide calibrated barrier transmission.\n\n"
                f"### 2. Top Material Candidate Evaluation\n"
                f"**Rank 1: {top_mat.material_name} ({top_mat.structure})** — Compatibility Score: **{top_mat.total_score}/100**\n"
                f"- **Moisture Barrier Performance**: WVTR of {specs.get('wvtr_g_m2_day')} g/m²·day (Score: {top_mat.score_breakdown.moisture_score}/100).\n"
                f"- **Gas Permeability Profile**: OTR of {specs.get('otr_cc_m2_day_atm')} cc/m²·day (Score: {top_mat.score_breakdown.oxygen_score}/100).\n"
                f"- **Key Merits**:\n- {reasons_str}\n\n"
                f"### 3. Engineering Trade-offs & Circularity Assessment\n"
                f"- **Circularity**: Recyclability classified as *{specs.get('recyclability')}* with carbon footprint of ~{specs.get('co2e_kg_per_kg', 'N/A')} kg CO₂e/kg.\n"
                f"- **Identified Trade-offs**:\n- {trade_offs_str}\n"
                f"- **Technical Warnings**:\n- {warnings_str}\n\n"
                f"### 4. Quality Control & Experimental Validation Requirements\n"
                f"1. **Food Contact Safety**: Verify food-grade resin compliance (e.g., FDA 21 CFR 177 / EU Regulation 10/2011) with the converter.\n"
                f"2. **Seal Integrity**: Conduct ASTM F88 peel strength and dye penetration leak tests for package hermeticity.\n"
                f"3. **Physical Shelf-Life Trial**: Perform real-time microbial challenge testing and sensory evaluation under target supply chain conditions."
            )

        return AIExplainResponse(
            explanation=explanation,
            provider="Deterministic Food Science Engine (Fallback)",
            model_name="deterministic-rule-engine-v1",
            generated_at=datetime.datetime.utcnow(),
            is_fallback=True,
            status_message=f"Deterministic fallback explanation generated ({reason})"
        )
